"""Initial migration

Revision ID: c2e45169f070
Revises: 
Create Date: 2025-08-24 23:27:42.578095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2e45169f070'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.alter_column('acadamic_year_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('academic_year_id'))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('academic_year_id'), ['acadamic_year_id'], unique=False)
        batch_op.alter_column('acadamic_year_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
